# Generated by Django 5.1.7 on 2025-04-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อ-นามสกุล')),
                ('position', models.CharField(max_length=100, verbose_name='ตำแหน่ง')),
                ('bio', models.TextField(verbose_name='ประวัติโดยย่อ')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='รูปภาพ')),
                ('order', models.IntegerField(default=0, verbose_name='ลำดับการแสดงผล')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
            ],
            options={
                'verbose_name': 'สมาชิกในทีม',
                'verbose_name_plural': 'สมาชิกในทีม',
                'ordering': ['order', 'id'],
            },
        ),
    ]
