# Generated by Django 5.1.7 on 2025-04-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='position',
        ),
        migrations.AddField(
            model_name='teammember',
            name='first_name',
            field=models.CharField(default='ชื่อ', max_length=100, verbose_name='ชื่อ'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='last_name',
            field=models.CharField(default='นามสกุล', max_length=100, verbose_name='นามสกุล'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='student_id',
            field=models.CharField(default='00000000', max_length=15, verbose_name='รหัสนักศึกษา'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='รูปภาพ'),
        ),
    ]
