# Generated by Django 5.1.7 on 2025-04-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_remove_teammember_bio_remove_teammember_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='ชื่อ'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='นามสกุล'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='student_id',
            field=models.CharField(max_length=15, verbose_name='รหัสนักศึกษา'),
        ),
    ]
