# Generated by Django 5.1.7 on 2025-04-10 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_alter_teammember_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/', verbose_name='รูปภาพ')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='คำอธิบายรูปภาพ')),
                ('order', models.IntegerField(default=0, verbose_name='ลำดับการแสดงผล')),
                ('is_main', models.BooleanField(default=False, verbose_name='เป็นรูปหลัก')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tourism.place', verbose_name='สถานที่ท่องเที่ยว')),
            ],
            options={
                'verbose_name': 'รูปภาพสถานที่ท่องเที่ยว',
                'verbose_name_plural': 'รูปภาพสถานที่ท่องเที่ยว',
                'ordering': ['order', 'id'],
            },
        ),
    ]
