# Generated by Django 5.1.7 on 2025-04-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_placeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='has_parking',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='has_restaurant',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='has_restroom',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='has_wifi',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
