# Generated by Django 5.1.7 on 2025-04-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_place_has_parking_place_has_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='map_embed',
            field=models.TextField(blank=True, help_text='ฝังโค้ด iframe จาก Google Maps', null=True),
        ),
    ]
